<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Disini</name>
   <tag></tag>
   <elementGuidId>e7c4e267-e5df-43ae-8a95-02c06337f52f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text-primary.ml-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginModal']/div/form/div/div[2]/div[4]/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Disini&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>85d3a9f4-7b0b-415b-83fe-286beb23b511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Signup</value>
      <webElementGuid>5c38b591-4470-41ca-ab2b-1e57513464b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-primary ml-2</value>
      <webElementGuid>60c684f3-c0ea-4e3d-a694-57e899d31500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disini</value>
      <webElementGuid>5ece6205-35ea-4830-a8b8-4f2ce7d8719e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginModal&quot;)/div[@class=&quot;modal-dialog&quot;]/form[1]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;text-center w-100 mt-2&quot;]/p[@class=&quot;text-muted font-weight-bold&quot;]/a[@class=&quot;text-primary ml-2&quot;]</value>
      <webElementGuid>c8132621-0fbb-474a-9f81-2b0f190f1f58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginModal']/div/form/div/div[2]/div[4]/p/a</value>
      <webElementGuid>f81c6162-22aa-4882-8299-3581210f04cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Disini')]</value>
      <webElementGuid>9747c254-c9f8-45a5-90b4-59e257e680b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[3]/following::a[1]</value>
      <webElementGuid>2f542bdf-8667-4ee5-83b0-461eb9480171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi:'])[1]/following::a[1]</value>
      <webElementGuid>7d5320ac-834d-43b1-97f6-7d975d4674f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/preceding::a[2]</value>
      <webElementGuid>cf90e517-4985-42cd-9047-e85ea08deb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disini']/parent::*</value>
      <webElementGuid>9f50f97a-183e-46a0-95e1-c272e69077d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'Signup')])[2]</value>
      <webElementGuid>f23df1a8-4e78-4162-ba44-03285f3e93cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>1c27cecb-92c5-4090-8287-000a64596551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Signup' and (text() = 'Disini' or . = 'Disini')]</value>
      <webElementGuid>24779997-c18a-45ce-aadf-1e8e5752b776</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
