<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Disini</name>
   <tag></tag>
   <elementGuidId>28daccf3-e728-45a3-8c22-2560325113e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text-primary.ml-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginModal']/div/form/div/div[2]/div[4]/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Disini&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f83f7e91-d5a0-469d-b3f3-72c80a3bbe2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Signup</value>
      <webElementGuid>3b30c952-e9bf-421b-bd05-d67dcd683f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-primary ml-2</value>
      <webElementGuid>880099fc-018a-468d-824c-46b0a1b362e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disini</value>
      <webElementGuid>b939b29e-d758-4f68-b501-88191d7ff77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginModal&quot;)/div[@class=&quot;modal-dialog&quot;]/form[1]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;text-center w-100 mt-2&quot;]/p[@class=&quot;text-muted font-weight-bold&quot;]/a[@class=&quot;text-primary ml-2&quot;]</value>
      <webElementGuid>018a0dda-1e65-483e-a47b-d0128fbd9a8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginModal']/div/form/div/div[2]/div[4]/p/a</value>
      <webElementGuid>16139ecd-59f1-47d1-bbc5-9bb68c80cab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Disini')]</value>
      <webElementGuid>598509b2-d2a1-46fd-9eb8-59a928960043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[3]/following::a[1]</value>
      <webElementGuid>46e6bd49-b3f0-4245-a13b-46e994055c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi:'])[1]/following::a[1]</value>
      <webElementGuid>0e32d4dd-b42e-4d3c-8ea3-c5632df85287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/preceding::a[2]</value>
      <webElementGuid>9956c212-8fd2-4fc0-9b67-fce6d99b5515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disini']/parent::*</value>
      <webElementGuid>766eb4c8-0f3e-4a7a-8a04-2fcf5aacb421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'Signup')])[2]</value>
      <webElementGuid>7fea2ce4-c6da-430f-a29b-553a4980a277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>246395c9-5667-4ea5-a778-c772aa8380e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Signup' and (text() = 'Disini' or . = 'Disini')]</value>
      <webElementGuid>0ad67456-f646-43ba-9364-6828ecaa33bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
