<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tambah Peserta_approve_peserta</name>
   <tag></tag>
   <elementGuidId>b17bbd07-14b1-42b0-9d59-f5e4d310ac1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#approve_peserta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='approve_peserta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#approve_peserta</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d513a74c-9f1f-4003-b5e4-b5b4b496c2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>51b851d9-5595-4a3d-9f0b-4937874b0ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>approve_peserta</value>
      <webElementGuid>b6c341a1-9b56-45ea-892c-f67b0c742076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>900e79e7-c62e-4649-8f5d-62fb5aa22e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approve_peserta&quot;)</value>
      <webElementGuid>6344c1f1-c0b3-4524-a949-ab21d9710088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='approve_peserta']</value>
      <webElementGuid>90b1ab01-8b4b-4776-b7be-5cd7e98d5415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='approve_peserta_container']/input</value>
      <webElementGuid>cb31ef98-3dcd-4717-aa6d-751a91523830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>09300dfe-f08e-4d7e-b9c1-cc915305f3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'approve_peserta' and @type = 'checkbox']</value>
      <webElementGuid>04f11d4e-502a-4517-8794-cd0228b62086</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
