<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_No SelectedLingkungan 1</name>
   <tag></tag>
   <elementGuidId>f0f7c936-4cb1-48a4-8fc9-c2a8157f2a85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lingkungan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='lingkungan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lingkungan</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>db78ac8d-0bcf-45a7-8a3d-fffa60d28be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lingkungan</value>
      <webElementGuid>fd75e964-1a09-41d5-9f28-e6002934c2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lingkungan</value>
      <webElementGuid>e94c4719-387d-41c4-91ff-b573b64a3c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-select bg-white border-left-0 border-md</value>
      <webElementGuid>e744515e-15ed-459c-9e62-825601cb8d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No SelectedLingkungan 1</value>
      <webElementGuid>610f3892-8aa9-43c8-9ecd-32afa54aafd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lingkungan&quot;)</value>
      <webElementGuid>8b0b51f5-333c-42e8-8ddb-c4c4f309c7d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='lingkungan']</value>
      <webElementGuid>ae623a6c-265d-4892-931d-126c2c7e7d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::select[4]</value>
      <webElementGuid>48d58a2e-fc3d-40b1-b45a-8a8aa0f02d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::select[4]</value>
      <webElementGuid>486739e9-c113-44b8-9f77-25713da21d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Peserta'])[1]/preceding::select[2]</value>
      <webElementGuid>0882f89f-4fee-4549-8d33-ddcc62a14d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Tambah Peserta'])[1]/preceding::select[2]</value>
      <webElementGuid>60ba20a6-8a42-4a55-9858-0caed49decb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/select</value>
      <webElementGuid>1e11739a-4102-44f4-9307-b41ccfee606c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'lingkungan' and @name = 'lingkungan' and (text() = 'No SelectedLingkungan 1' or . = 'No SelectedLingkungan 1')]</value>
      <webElementGuid>035e4aa1-e3a2-406a-9c3c-b8656993751c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
