<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_No SelectedParoki CidengParoki Kampu_3d36e7</name>
   <tag></tag>
   <elementGuidId>12a76f81-40ea-4724-a369-566435927922</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paroki</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='paroki']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#paroki</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>65ef1f88-a858-4be0-93b3-e2119fb71f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paroki</value>
      <webElementGuid>06c59be0-b7b9-4d8c-a437-d90f65f65f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paroki</value>
      <webElementGuid>87cdfb9e-6c36-4b39-a203-53a5076947ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-select bg-white border-left-0 border-md</value>
      <webElementGuid>61c8ecd3-7f89-4abd-8960-7fb36f91fddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No SelectedParoki CidengParoki Kampung DuriParoki SlipiParoki Toasebio</value>
      <webElementGuid>09106d43-6550-4295-bfe2-48a41d91cc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paroki&quot;)</value>
      <webElementGuid>dafe92b9-8de9-4cdd-801d-535e76093dfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='paroki']</value>
      <webElementGuid>e41dac7b-593a-4e81-9c22-1ba266e308b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::select[2]</value>
      <webElementGuid>ac730240-9ceb-4be9-a4de-b4f73554e7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::select[2]</value>
      <webElementGuid>97049547-0a7a-41b2-8c35-5305812dddb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Peserta'])[1]/preceding::select[4]</value>
      <webElementGuid>791d7015-fee6-4fbc-addc-6d71da7af872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Tambah Peserta'])[1]/preceding::select[4]</value>
      <webElementGuid>72ae1b81-5cd1-46db-a9e9-c2bf6d4e03aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>1705be59-1c70-494c-b80e-7e117257d6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'paroki' and @name = 'paroki' and (text() = 'No SelectedParoki CidengParoki Kampung DuriParoki SlipiParoki Toasebio' or . = 'No SelectedParoki CidengParoki Kampung DuriParoki SlipiParoki Toasebio')]</value>
      <webElementGuid>0dabb123-ee4b-4c1b-b337-01c5a5297dd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
