<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_No SelectedWilayah 1</name>
   <tag></tag>
   <elementGuidId>afae8d7a-f808-499d-ba89-785ece1f982b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wilayah</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='wilayah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#wilayah</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e72c35e9-d3e9-4189-a45e-f29020d7b6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wilayah</value>
      <webElementGuid>eea51ad7-fa5d-4a2e-ba80-4b9025851b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wilayah</value>
      <webElementGuid>0f7aa95f-e91e-487a-b0c9-e2e9e767dba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-select bg-white border-left-0 border-md</value>
      <webElementGuid>fb8333e2-3ee2-4573-8e38-c464718fb81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No SelectedWilayah 1</value>
      <webElementGuid>bc8c8998-b2c7-449f-ad2a-c247f75afab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wilayah&quot;)</value>
      <webElementGuid>aae6ecd4-c8a4-4077-8956-4d8a1895315f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='wilayah']</value>
      <webElementGuid>933e8bcf-c1d5-4a60-a6df-835d253b4a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::select[3]</value>
      <webElementGuid>a744293a-7061-4afb-a8ea-aa994e1b2823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::select[3]</value>
      <webElementGuid>fe3a6564-e777-4ee9-bd35-6860efb7f7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Peserta'])[1]/preceding::select[3]</value>
      <webElementGuid>994f2a51-0806-4377-b2c5-ec1fdc72a331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Tambah Peserta'])[1]/preceding::select[3]</value>
      <webElementGuid>7dd551cd-10c1-410e-a8af-39913ea4f243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>f477ff14-61c7-475a-b15d-a2a0e15afc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'wilayah' and @name = 'wilayah' and (text() = 'No SelectedWilayah 1' or . = 'No SelectedWilayah 1')]</value>
      <webElementGuid>130f7395-1eb1-4927-8f62-81103dce094f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
